config/routes.rb
Rails.application.routes.draw do
  root 'static#home'
  get 'signup' => 'static#signup', as: "new_user"
  post 'login' => 'sessions#login', as: "login"
  post 'logout' => 'sessions#logout', as: "logout"
  get 'auth/github/callback' => 'sessions#create'
  resources :users, except: [:new, :edit, :index]
  get 'users/new' => 'static#signup'
  resources :posts, except: [:edit] do
    resources :comments, only: [:create, :update, :destroy, :index, :show]
    resources :appointments, only: [:new, :create, :update, :destroy]
  end
  get 'appointments/available' => 'appointments#available', as: "available_appointments"
  resources :appointments, only: [:show] do
    resources :volunteers, only: [:create, :update, :destroy]
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :content, length: {in: 1..1000, message: "keep your comment content between 1 and 1000 characters."}
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_login
  before_action :find_post
  before_action :find_comment, only:[:show, :update, :destroy]
  
  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      render json: @comment, status: 200
    else
      render json: {response: 'invalid comment'}, status: 400
    end
  end

  def show
    render json: @comment, status: 200
  end

  def index
    render json: @post.comments, status: 200
  end

  def update
    if @comment.update(comment_params)
      render json: @comment, status: 200
    else
      render json: {response: 'invalid comment params'}, status: 400
    end
  end

  def destroy
    if @comment.user_id == session[:user_id]
      Comment.destroy(params[:id])
      render status: 200
    else
      render json: {response: 'invalid user'}, status: 400
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:user_id, :post_id, :content)
  end
  
  def find_post
    @post = Post.find(params[:post_id])
    flash[danger: "not a valid post"] unless @post
  end

  def find_comment
    @comment = Comment.find(params[:id])
    flash[danger: "not a valid comment"] unless @comment
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<br>
<%= content_tag(:div, class:["post_comment"]) do %>
  <% if is_current_user?(comment.user) %>
    <%= render partial: "comments/form", locals: {comment: comment} %>
  <% else %>
    <p>"<%= comment.content %>" comment from <%= link_to comment.user.name, user_path(comment.user) %></p>
  <% end %>
<% end %>

app/views/comments/_form.html.erb
<%= form_for([@post, comment]) do |f| %>
  <%= f.hidden_field :user_id, :value => current_user %>
  <%= f.hidden_field :post_id, :value => @post.id %>
  <p><%= f.text_area :content, size: "100x10" %></p>
  <%= f.submit %>
<% end %><br>
<% if comment.id %>
  <%= button_to 'Delete Comment', post_comment_path(@post, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>