config/routes.rb
Rails.application.routes.draw do
  root 'static#home'
  get 'signup' => 'static#signup', as: "new_user"
  post 'login' => 'sessions#login', as: "login"
  post 'logout' => 'sessions#logout', as: "logout"
  get 'auth/github/callback' => 'sessions#create'
  resources :users, except: [:new, :edit, :index]
  get 'users/new' => 'static#signup'
  resources :posts, except: [:edit] do
    resources :comments, only: [:create, :update, :destroy, :index, :show]
    resources :appointments, only: [:new, :create, :update, :destroy]
  end
  get 'appointments/available' => 'appointments#available', as: "available_appointments"
  resources :appointments, only: [:show] do
    resources :volunteers, only: [:create, :update, :destroy]
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :appointments, dependent: :destroy
  accepts_nested_attributes_for :appointments
  has_many :volunteers, through: :appointments
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :content, length: {in: 10..1000, message: "keep your post content between 10 and 1000 characters."}
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login, except:[:index]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = helpers.current_user
    if @post.save
      redirect_to @post, flash: {success: "Successfully created Post"}
    else
      flash[:danger] = @post.errors.full_messages.join(", ")
      render :new
    end
  end

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    unless @post
      redirect_to home_path, flash:{error: "Not a valid Post"}
    end
    @appointments = @post.appointments
    respond_to do |format|
      format.json {render json: @post, status: 200}
      format.html {render :show, status: 200}
    end
  end

  def update
    @post = Post.find(params[:id])
    if @post && @post.update(post_params)
      flash[:success] = "Successfully edited Post"
    else
      flash[:danger] = @post.errors.full_messages.join(", ")
    end
    redirect_to @post
  end


  def destroy
    if Post.find(params[:id])
      Post.destroy(params[:id])
      flash[:success] = "Successfully deleted post"
    else
      flash[:danger] = "Invalid Post to delete"
    end
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:user_id, :title, :content, appointments_attributes:
      [:title, :spots, :info, :start_date, :end_date, :volunteers_count])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_display_info.html.erb
<%= content_tag(:div, class:["post_info"]) do %>
  <h3><%= post.title %></h3><br>
  <p><%= post.content %></p><br>
<% end %>

app/views/posts/_form.html.erb
<%= content_tag(:div, class:["post_form"]) do %>
  <%= form_for @post do |f| %>
    <p><%= f.label :title %><%= f.text_field :title %></p>
    <p><%= f.label :content %></p>
    <p><%= f.text_area :content, size: "100x10" %></p>
    <%= f.submit %>
  <% end %>
<% end %>

app/views/posts/_new_form.html.erb
<%= content_tag(:div, class:["new_post_form"]) do %>
  <%= form_for @post do |f| %>
    <p>This form is for signing up any place that you have where you might want volunteer help from the lovely users of Help Y!</p>
    <p>Title your place to attract potential volunteers <%= f.text_field :title %></p>
    <p>Where is your place? What hobbies do you have? What is important to you? What do you want to accomplish with potential volunteers?</p>
    <p>Tell us about yourself and your life. Volunteers want to get to know kind and interesting people, let them know about you and your mission.</p>
    <p><%= f.text_area :content, size: "100x10" %></p>
    <p>If you want to make a new volunteer appointment with this post, fill out the information below:</p>
    <%= f.fields_for :appointments, @post.appointments.build do |appointments_fields| %>
    <p>Enter a title for your volunteer opportunity, something that tells a user what they'll be doing <%= appointments_fields.text_field :title %></p>
    <p>How many people will you be looking to host <%= appointments_fields.text_field :spots, required: true %></p>
    <p>Tell us a bit more about what you plan for people who come to stay with you. While you host them, what will daily life be like?</p>
    <p>This is a great opportunity to list your expectations and accomodations, past volunteer experiences if you have any!</p>
    <p><%= appointments_fields.text_area :info, size: "100x10" %></p>
    <p>When will you want volunteers to first arrive?<%= appointments_fields.date_select :start_date %></p>
    <p>And when will you stop hosting volunteers?<%= appointments_fields.date_select :end_date %></p>
    <%# <%= f.time_zone_select :timezone %>
    <%= f.submit %>
    <% end %>
  <% end %>
<% end %>

app/views/posts/_post.html.erb
<%= render partial: 'posts/display_info', locals: { post: post } %>
<p>
  <%= button_to "See post's page", post_path(post), method: :get %>
</p>
<div id="<%=post.id%>-comments" class="post-comments">
  <input class="get-post-comments" type="submit" value="See post's comments" data-id=<%=post.id%> />
</div>

app/views/posts/index.html.erb
<h1>All Posts</h1><br>
<%  if logged_in?  %>
  <%= button_to "Create Post", new_post_path, method: :get %>
<% end %><br>
<%= render @posts %>
<script id="comment-template" type="text/x-handlebars-template">
  <div class="comment-content">
    <h4>{{content}}</h4>
    <div class="comment-data">
      written by: <a href="/users/{{user.id}}">{{user.name}}</a>
    </div>
  </div>
</script>
<% content_for :js do %>
  <%= javascript_include_tag 'post', 'data-turbolinks-track': 'reload' %>
<% end %>

app/views/posts/new.html.erb
<%= render "new_form" %>

app/views/posts/show.html.erb
<% if is_current_user?(@post.user) %>
  <%= render 'form' %>
<% else %>
  <%= render partial: 'display_info', locals: {post: @post} %>
<% end %>
<div id="new-comment"></div>
<div id="comments"></div>
<div id="comments-clear"><input type="submit" value="Clear Comments" /></div>
<%= button_to "Load Comments", post_comments_path(@post), {method: :get, form_class: "get-comments"} %>
<%= content_tag(:h3, "Volunteer Opportunities") unless @appointments.blank? %>
<%= render partial: 'appointments/post_appointment', collection: @appointments, as: :appointment %><br>
<% if is_current_user?(@post.user) %>
  <%= button_to "Create a new Appointment", new_post_appointment_path(@post), method: :get %><br>
  <%= button_to 'Delete Post', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

<script id="comment-template" type="text/x-handlebars-template">
  <div class="comment-content">
    <h4>{{content}}</h4>
    <div class="comment-data">
      written by: <a href="/users/{{user.id}}">{{user.name}}</a>, last edited: {{updated_at}}
    </div>
    {{#if isCurrentUser }}
      <form action="/posts/<%=@post.id%>/comments/{{id}}" method="get" class="edit-comment-form">
        <input type="submit" value="Edit Comment" />
      </form>
    {{/if}}
  </div>
</script>
<script id="form-template" type="text/x-handlebars-template">
  <form action="/posts/<%=@post.id%>/comments{{#if id}}/{{id}}{{/if}}" method="post" class="{{#if id}}update{{else}}new{{/if}}-comment-form">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <input type="hidden" name="comment[post_id]" value="<%= @post.id %>">
  <input type="hidden" name="comment[user_id]" value="<%= current_user %>">
  <label for='comment[content]'>content:</label>
  <textarea class="comment-content-text" name='comment[content]', cols="100", rows="10">{{content}}</textarea>
  <p><input class="{{#if id}}update{{else}}create{{/if}}" type="submit" value="{{#if id}}Update{{else}}Create{{/if}} Comment" /></p>
</script>
<script id="new-comment-button-template" type="text/x-handlebars-template">
  <input id="new-comment-button" type="submit" value="Add New Comment" />
</script>
<% content_for :js do %>
  <%= javascript_include_tag 'comment', 'data-turbolinks-track': 'reload' %>
<% end %>