config/routes.rb
Rails.application.routes.draw do
  root 'static#home'
  get 'signup' => 'static#signup', as: "new_user"
  post 'login' => 'sessions#login', as: "login"
  post 'logout' => 'sessions#logout', as: "logout"
  get 'auth/github/callback' => 'sessions#create'
  resources :users, except: [:new, :edit, :index]
  get 'users/new' => 'static#signup'
  resources :posts, except: [:edit] do
    resources :comments, only: [:create, :update, :destroy, :index, :show]
    resources :appointments, only: [:new, :create, :update, :destroy]
  end
  get 'appointments/available' => 'appointments#available', as: "available_appointments"
  resources :appointments, only: [:show] do
    resources :volunteers, only: [:create, :update, :destroy]
  end
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :post
  has_many :volunteers
  has_many :users, through: :volunteers

  validates :info, length: {in: 1..1000, message: "keep your comment info between 1 and 1000 characters."}
  validates :spots, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
  validates :start_date, date: { after_or_equal_to: Proc.new { Date.today }, message: 'cannot be before today\'s date' }, on: :create
  validates :end_date, date: { after: :start_date, message: 'must be after start date' }
  validates :volunteers_count, numericality: { less_than_or_equal_to: :spots }

  def days_left
    (end_date - Date.today).to_i
  end

  def spots_left
    spots - volunteers_count.to_i if spots
  end

  def display_date(date)
    date.strftime("%B %-d %Y at %I:%M %P")
  end

  def active?
    days_left > 0
  end

  def full?
    spots == volunteers_count
  end

  def available?
    active? && !full?
  end

  def owner_id
    self.post.user_id
  end

  def owner_name
    self.post.user.name
  end

  def active_string
    case
    when !active?
      "Closed, appointment end date has passed."
    when active? && full?
      "Active, but full of volunteers. consider emailing the post creator if you're really interested."
    when available?
      "Open for #{days_left} more days and ready to take #{spots_left} volunteers!"
    end
  end

  def has_user?(user_id)
    volunteers.any?{|v| v.user_id = user_id}
  end

  def self.available
    where("end_date >= ?", Time.now) & where.not("volunteers_count = spots").order(end_date: :asc)
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :require_login
  before_action :find_post, except: [:available, :show]
  before_action :find_appointment, except: [:available, :new, :create]

  def new
    @appointment = @post.appointments.build
    unless helpers.is_current_user?(@post.user)
      redirect_to posts_path, flash: {danger: "You are not authorized to make that appointment"}
    end
    render :new
  end

  def create
    @appointment = Appointment.create(appointment_params)
    if @appointment.valid?
      flash[:success] = "Successfully created appointment"
      redirect_to post_path(params[:post_id])
    else
      flash[:danger] = @appointment.errors.full_messages.join(", ")
      render :new
    end
  end

  def show
    redirect_to available_appointments_path, flash: {danger: "No such appointment"} unless @appointment
    respond_to do |format|
      format.json {render json: @appointment, status: 200}
      format.html {
        if @appointment.has_user?(helpers.current_user)
          @volunteer = Volunteer.find_by(appointment_id: @appointment.id, user_id: helpers.current_user) 
        else
          @volunteer = Volunteer.new
        end
        render :show, status: 302
      }
    end
  end

  def available
    respond_to do |format|
      format.json {render json: Appointment.available, status: 200}
      format.html {render :available, status: 200}
    end
  end

  def update
    if @appointment.update(appointment_params)
      flash[:success] = "Successfully edited appointment"
    else
      flash[:danger] = @appointment.errors.full_messages.join(", ")
    end
    redirect_to post_path(params[:post_id])
  end

  def destroy
    if @appointment.owner_id == helpers.current_user
      Appointment.destroy(params[:id])
      flash[:success] = "Successfully deleted appointment"
    else
      flash[:danger] = "Cannot delete appointment"
    end
    redirect_to post_path(params[:post_id])
  end

  private

  def appointment_params
    params.require(:appointment).permit(:post_id, :spots, :start_date, :end_date, :info, :title)
  end

  def find_post
    @post = Post.find(params[:post_id])
    flash[danger: "not a valid post"] unless @post
  end

  def find_appointment
    @appointment = Appointment.find(params[:id])
    flash[danger: "not a valid appointment"] unless @appointment
  end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_appointment.html.erb
<br>
<%= content_tag(:div, class:["appointment"]) do %>
  <h3><%= appointment.title %></h3>
  <p>information: <%= appointment.info %></p>
  <p>status: <%= appointment.active_string %><p>
  <p>from: <%= appointment.display_date(appointment.start_date) %> - <%= appointment.display_date(appointment.end_date) %><p>
  <p>created on: <%= appointment.display_date(appointment.created_at) %><p>
  <%= button_to "more information", appointment_path(appointment), method: :get %>
<% end %>

app/views/appointments/_display_info.html.erb
<%= content_tag(:div, class:["appointment_info"]) do %>
  <h1><%= appointment.title %></h1>
  <p><%= appointment.post.user.name %> requests <%= appointment.spots %> volunteers from 
    <strong><%= appointment.display_date(appointment.start_date) %> to <%= appointment.display_date(appointment.end_date) %></strong></p>
  <p>information: <%= appointment.info %></p>
  <p>spots left: <%= appointment.spots_left %></p>
  <p>created on: <%= appointment.display_date(appointment.created_at) %><p>
  <p>last updated on: <%= appointment.display_date(appointment.updated_at) %><p>
  <p><%= link_to "post page (might have similar volunteer opportunities)", post_path(appointment.post) %></p>
  <p><%= link_to "owner's page", user_path(appointment.post.user) %></p>
<% end %>

app/views/appointments/_form.html.erb
<%= content_tag(:div, class:["appointment_form"]) do %>
  <%= form_for([@post, appointment]) do |f| %>
    <%= f.hidden_field :post_id, :value => @post.id %>
    <p>
      <%= f.label :title %> <%= f.text_field :title %> 
      <%= f.label :spots, required: true %> <%= f.number_field :spots %>
      <%= f.label :spots_left %> <%= appointment.spots_left %>
    </p>
    <p>
      <%= f.label :start_date %> <%= f.date_select :start_date %> 
      <%= f.label :end_date %> <%= f.date_select :end_date %> 
    </p>
    <p><%= f.label :info %><br><%= f.text_area :info, size: "100x10" %></p>
    <%= f.submit %>
  <% end %><br>
  <%= button_to 'Delete Appointment', post_appointment_path(@post, appointment), method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

app/views/appointments/_new_form.html.erb
<%= content_tag(:div, class:["new_post_appointment_form"]) do %>
  <%= form_for([@post, @appointment]) do |f| %>
    <%= f.hidden_field :post_id, :value => @post.id %>
    <p>Enter a title for your volunteer opportunity, something that tells a user what they'll be doing <%= f.text_field :title %></p>
    <p>How many people will you be looking to host <%= f.number_field :spots, required: true %></p>
    <p>Tell us a bit more about what you plan for people who come to stay with you. While you host them, what will daily life be like?</p>
    <p>This is a great opportunity to list your expectations and accomodations, past volunteer experiences if you have any!</p>
    <p><%= f.text_area :info, size: "100x10" %></p>
    <p>When will you want volunteers to first arrive?<%= f.date_select :start_date %></p>
    <p>And when will you stop hosting volunteers?<%= f.date_select :end_date %></p>
    <%= f.submit %>
  <% end %>
<% end %>

app/views/appointments/_post_appointment.html.erb
<% if is_current_user?(@post.user) %>
  <%= render partial: "appointments/form", locals: {appointment: appointment} %>
<% else %>
  <%= render partial: 'appointments/appointment', locals: {appointment: appointment} %>
<% end %>

app/views/appointments/available.html.erb
<h1>All available Volunteer Opportunities</h1>

<div class="appointments"></div>

<script id="appointment-template" type="text/x-handlebars-template">
  <div class="appointment-content">
    <h2>{{title}}</h2>
    <h4>{{info}}</h4>
    <div class="appointment-data">
      from post: <a href="/posts/{{post.id}}">{{post.title}}</a>, <a href="/users/{{owner_id}}">{{owner_name}}</a>'s profile 
    </div>
    <input type="submit" value="More Info" class="more-info-button" data-id={{availableId}} data-fullid={{id}} />
  </div>
</script>
<script id="full-appointment-template" type="text/x-handlebars-template">
  <div class="appointment-content">
    <h2>{{title}}</h2>
    <h4>{{info}}</h4>
    <div class="appointment-data">
      <p>There are {{spots_left}} available spots for this opportunity</p>
      <p>Start Date: {{start_date}}</p>
      <p>End Date: {{end_date}}</p>
      <p>from post: <a href="/posts/{{post.id}}">{{post.title}}</a></p>
      <p>created by user: <a href="/users/{{owner_id}}">{{owner_name}}</a></p>
      <p>would you like to sign up to volunteer for this opportunity?</p>
      <form action="/appointments/{{id}}" method="get" class="volunteer-button">
        <input type="submit" value="Volunteer!" />
      </form>
    </div>
    <input type="submit" value="Next Volunteer Opportunity" id="next-info-button"/>
    <input type="submit" value="Last Volunteer Opportunity" id="last-info-button"/>
    <input type="submit" value="All Volunteer Opportunities" id="all-info-button"/>
  </div>
</script>
<% content_for :js do %>
  <%= javascript_include_tag 'appointment', 'data-turbolinks-track': 'reload' %>
<% end %>

app/views/appointments/index.html.erb
<h1>All Volunteer Opportunities</h1>
<%= render @appointments %>

app/views/appointments/new.html.erb
<%= render partial: "new_form" %>

app/views/appointments/show.html.erb
<%= render partial: 'appointments/display_info', locals: { appointment: @appointment } %>
<% if %>
  <%= render 'volunteers/signup' if @appointment.available? || @appointment.has_user?(current_user) %>
<% end %>