config/routes.rb
Rails.application.routes.draw do
  root 'static#home'
  get 'signup' => 'static#signup', as: "new_user"
  post 'login' => 'sessions#login', as: "login"
  post 'logout' => 'sessions#logout', as: "logout"
  get 'auth/github/callback' => 'sessions#create'
  resources :users, except: [:new, :edit, :index]
  get 'users/new' => 'static#signup'
  resources :posts, except: [:edit] do
    resources :comments, only: [:create, :update, :destroy, :index, :show]
    resources :appointments, only: [:new, :create, :update, :destroy]
  end
  get 'appointments/available' => 'appointments#available', as: "available_appointments"
  resources :appointments, only: [:show] do
    resources :volunteers, only: [:create, :update, :destroy]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Help Y</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield :js %>
  </head>
  <body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
        <a class="navbar-brand" href="<%= root_url %>"/>Home</a>
        <% if logged_in? %>
          <%= link_to "Your account", user_path(current_user), class: ["navbar-brand","user-link"] %>
          <%= link_to "Log out", logout_path, method: 'post', class: "navbar-brand"%>
          <%= link_to 'All available volunteer opportunities', available_appointments_path, class: "navbar-brand", data: { turbolinks: "false"} %>
        <% else %>
          <%= link_to "Sign in with Github", '/auth/github', class: "navbar-brand" %>
          <%= link_to "Log in", root_path, class: "navbar-brand" %>
          <%= link_to "Create a new account", new_user_path, class: "navbar-brand" %>
        <% end %>
        <%= link_to 'All posts', posts_path, class: "navbar-brand" %>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">

          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <!-- content -->
    <div class="container"  role="main">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>